#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done

# Handle SIGINT (Ctrl+C) signals
trap 'echo "Y U no love me?!"' SIGINT

# Handle SIGTERM and SIGQUIT signals
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit 1' SIGTERM SIGQUIT

# Wait for a signal
wait
