#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond process

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
# Send a termination signal to the process
  kill -TERM "$pid"
fi

