#!/usr/bin/env bash

# Trap the SIGTERM signal so that we can display a message when we receive it.
trap 'echo "I am invincible!!!"' SIGTERM

# Start an infinite loop to display the message.
while true; do
  echo "To infinity and beyond"
  sleep 2
done

