#!/usr/bin/env bash

# Function to handle SIGTERM signal
function sigterm_handler() {
  echo "I am invincible!!!"
  exit 0
}

# Trap the SIGTERM signal and call the sigterm_handler function
trap 'sigterm_handler' SIGTERM

# Loop indefinitely with a 2-second pause between each iteration
while true; do
  echo "To infinity and beyond"
  sleep 2
done

