#!/usr/bin/env bash

# Find the PID of the 7-highlander process
pid=$(ps aux | grep "7-highlander.sh" | grep -v grep | awk '{print $2}')

if [ -n "$pid" ]; then
# Send a SIGTERM signal to the process
  kill -TERM "$pid"
fi

